In [1]:
from app.data.etl import GetData
from app.data.feature_engineering import FeatureEngineering

In [2]:
get_data = GetData(file_path='app/data/raw_data/BD_ordenes.xlsx')
df = get_data.read_data()

In [3]:
df.head()

,respuesta,consumo_criticado,servicio,categoria,nivel_tension,estrato,localidad,funcion_analisis,calificacion,obs_lectura,periodicidad
0,1,0.0,701-ENERGÍA MDO REGULADO,3-INDUSTRIAL,220.0,NaN,5088-BELLO,CALCCOPR - Calcular Consumo Penalizado de Ener...,5035-BAJO ENERGIA (<-50%),30-VARIACION NIVEL DE UTILIZACIÓN,1
1,1,420.0,701-ENERGÍA MDO REGULADO,3-INDUSTRIAL,220.0,NaN,5088-BELLO,CALCCOPR - Calcular Consumo Penalizado de Ener...,5080-MUY ALTO (>500%),30-VARIACION NIVEL DE UTILIZACIÓN,1
2,1,99999.0,101-AGUA POTABLE,1-RESIDENCIAL,NaN,1.0,5088-BELLO,CALCCOLE - Calcular Consumo por Lecturas,5080-MUY ALTO (>500%),34-LECTURA MENOR,1
3,1,881.0,701-ENERGÍA MDO REGULADO,3-INDUSTRIAL,220.0,NaN,5088-BELLO,CALCCOLE - Calcular Consumo por Lecturas,5080-MUY ALTO (>500%),35-NO HAY JUSTIFICACION,1
4,1,99999.0,701-ENERGÍA MDO REGULADO,1-RESIDENCIAL,220.0,4.0,5001-MEDELLÍN,CALCCOLE - Calcular Consumo por Lecturas,5080-MUY ALTO (>500%),34-LECTURA MENOR,1

# Feature Engineering

In [4]:
feature_engineering = FeatureEngineering(df)
df_fe, target_variable, numeric_features, categorical_features = feature_engineering.prepare_features_only_energy()

In [5]:
print("Numeric features:", numeric_features)
print("Categorical features:", categorical_features)
print("Target variable:", target_variable)

Numeric features: ['consumo_criticado', 'nivel_tension', 'estrato', 'periodicidad']
Categorical features: ['categoria', 'localidad', 'funcion_analisis', 'calificacion', 'obs_lectura', 'tipo_servicio']
Target variable: respuesta

In [6]:
df_fe.head()

,respuesta,consumo_criticado,categoria,nivel_tension,estrato,localidad,funcion_analisis,calificacion,obs_lectura,periodicidad,tipo_servicio
0,0,0.0,3-INDUSTRIAL,220.0,NaN,5088-BELLO,CALCCOPR - Calcular Consumo Penalizado de Ener...,5035-BAJO ENERGIA (<-50%),30-VARIACION NIVEL DE UTILIZACIÓN,1,Energia
1,0,420.0,3-INDUSTRIAL,220.0,NaN,5088-BELLO,CALCCOPR - Calcular Consumo Penalizado de Ener...,5080-MUY ALTO (>500%),30-VARIACION NIVEL DE UTILIZACIÓN,1,Energia
3,0,881.0,3-INDUSTRIAL,220.0,NaN,5088-BELLO,CALCCOLE - Calcular Consumo por Lecturas,5080-MUY ALTO (>500%),35-NO HAY JUSTIFICACION,1,Energia
4,0,99999.0,1-RESIDENCIAL,220.0,4.0,5001-MEDELLÍN,CALCCOLE - Calcular Consumo por Lecturas,5080-MUY ALTO (>500%),34-LECTURA MENOR,1,Energia
7,0,260.0,3-INDUSTRIAL,220.0,NaN,5088-BELLO,CALCCOLE - Calcular Consumo por Lecturas,5035-BAJO ENERGIA (<-50%),30-VARIACION NIVEL DE UTILIZACIÓN,1,Energia

In [7]:
test_size = 0.2

# Modelo con MLFlow + Optuna

Antes de ejecutar, subir cliente de MLFlow con el comando.

* mlflow server --backend-store-uri sqlite:///consumos.db

In [8]:
from sklearn.ensemble import RandomForestClassifier
from app.train.train import TrainModel
import mlflow

mlflow.set_tracking_uri("http://127.0.0.1:5000")

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [9]:
# Define RandomForest parameter distributions
param_distributions = {
    'n_estimators': ('int', 50, 200),
    'max_depth': ('int', 5, 30),
    'min_samples_split': ('int', 2, 10),
    'min_samples_leaf': ('int', 1, 5),
    'max_features': ('categorical', ['sqrt', 'log2', None])
}

trainer = TrainModel(
    df_fe,
    numeric_features = numeric_features,
    categorical_features = categorical_features,
    target_column = target_variable,
    model_class = RandomForestClassifier,
    test_size = test_size,
    model_params = {'random_state': 42, 'n_jobs': -1},
    param_distributions = param_distributions,
    n_trials = 50,
    optimization_metric = 'f1',
    mlflow_setup = mlflow,
    mlflow_experiment_name = 'experimento_desviacion_consumos',
    mlflow_tracking_uri = 'http://localhost:5000'
)

best_pipeline, run_id, study = trainer.train()

[I 2025-10-18 17:20:34,513] A new study created in memory with name: optuna_RandomForestClassifier
/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/src/app/train/train.py:187: ExperimentalWarning: MLflowCallback is experimental (supported from v1.4.0). The interface can change in the future.
  mlflow_callback = MLflowCallback(
INFO:app.train.train:Starting Optuna optimization with 50 trials...
INFO:app.train.train:Optimizing for: f1
INFO:app.train.train:Model type: RandomForestClassifier
/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:35,512] Trial 0 finished with value: 0.8222175631706217 and parameters: {'n_estimators': 130, 'max_depth': 21, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 0 with value: 0.8222175631706217.
2025/10/18 17:20:35 INFO mlflow.tracking.fluent: Experiment with name 'optuna_RandomForestClassifier' does not exist. Creating a new experiment.

🏃 View run 0 at: http://127.0.0.1:5000/#/experiments/1/runs/c5a494d24e5949739b46bdd28fafadf3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:36,827] Trial 1 finished with value: 0.8220859617125831 and parameters: {'n_estimators': 159, 'max_depth': 16, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 0 with value: 0.8222175631706217.

🏃 View run 1 at: http://127.0.0.1:5000/#/experiments/1/runs/39e92241c7b5425abd9c1ab273f27a24
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:37,133] Trial 2 finished with value: 0.8071757569079356 and parameters: {'n_estimators': 180, 'max_depth': 27, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 0 with value: 0.8222175631706217.
/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:37,363] Trial 3 finished with value: 0.6024893001678888 and parameters: {'n_estimators': 164, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8222175631706217.

🏃 View run 2 at: http://127.0.0.1:5000/#/experiments/1/runs/ff7d8a0592de459ea3e3292cfaeb828e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:37,561] Trial 4 finished with value: 0.8056466982919643 and parameters: {'n_estimators': 106, 'max_depth': 22, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 0 with value: 0.8222175631706217.

🏃 View run 3 at: http://127.0.0.1:5000/#/experiments/1/runs/7d149d9e7dc1445582f5fbd3950f0f7c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run 4 at: http://127.0.0.1:5000/#/experiments/1/runs/f7703edc47c44aa3a1f680db5251e4e6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:37,769] Trial 5 finished with value: 0.816163474447089 and parameters: {'n_estimators': 100, 'max_depth': 21, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 0 with value: 0.8222175631706217.
/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:37,933] Trial 6 finished with value: 0.6247082519432393 and parameters: {'n_estimators': 101, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 0 with value: 0.8222175631706217.

🏃 View run 5 at: http://127.0.0.1:5000/#/experiments/1/runs/7997902262924ce999813e0b808730b7
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run 6 at: http://127.0.0.1:5000/#/experiments/1/runs/54e4c0ded89f437c88a409040b7ad378
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:38,155] Trial 7 finished with value: 0.7795895957993354 and parameters: {'n_estimators': 133, 'max_depth': 16, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 0 with value: 0.8222175631706217.

🏃 View run 7 at: http://127.0.0.1:5000/#/experiments/1/runs/7298cc94317a471591a18590c70150b3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:39,183] Trial 8 finished with value: 0.8215447602003596 and parameters: {'n_estimators': 126, 'max_depth': 27, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 0 with value: 0.8222175631706217.
/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:39,358] Trial 9 finished with value: 0.8245712400967026 and parameters: {'n_estimators': 65, 'max_depth': 24, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 9 with value: 0.8245712400967026.

🏃 View run 8 at: http://127.0.0.1:5000/#/experiments/1/runs/303daa182dc54baaa190fdb63dd879eb
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run 9 at: http://127.0.0.1:5000/#/experiments/1/runs/95f80ca6de5342bfa11f39aa7801aead
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:39,521] Trial 10 finished with value: 0.810060011873601 and parameters: {'n_estimators': 50, 'max_depth': 30, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_features': 'sqrt'}. Best is trial 9 with value: 0.8245712400967026.
/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:39,668] Trial 11 finished with value: 0.8065981067044762 and parameters: {'n_estimators': 54, 'max_depth': 23, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 9 with value: 0.8245712400967026.

🏃 View run 10 at: http://127.0.0.1:5000/#/experiments/1/runs/e9e264be65b44b368e0b41a4e041da37
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run 11 at: http://127.0.0.1:5000/#/experiments/1/runs/ca4eddb5c9544970a31aadb02521f63d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:40,171] Trial 12 finished with value: 0.823575537293726 and parameters: {'n_estimators': 78, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 9 with value: 0.8245712400967026.
/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:40,328] Trial 13 finished with value: 0.7629535393845673 and parameters: {'n_estimators': 74, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 'sqrt'}. Best is trial 9 with value: 0.8245712400967026.

🏃 View run 12 at: http://127.0.0.1:5000/#/experiments/1/runs/1d3af27a5eb3491b89d2d9ef9748204b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run 13 at: http://127.0.0.1:5000/#/experiments/1/runs/4225ad1143fc4b48866d49ab8821b407
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:40,839] Trial 14 finished with value: 0.824846400787152 and parameters: {'n_estimators': 79, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 14 with value: 0.824846400787152.
/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:41,015] Trial 15 finished with value: 0.7818934378951641 and parameters: {'n_estimators': 80, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 14 with value: 0.824846400787152.

🏃 View run 14 at: http://127.0.0.1:5000/#/experiments/1/runs/dc8175a1258c48c781055c9bc8f4e942
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run 15 at: http://127.0.0.1:5000/#/experiments/1/runs/b6bae62f671b4c5b9905019e9a43bd0b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:41,509] Trial 16 finished with value: 0.824660654216422 and parameters: {'n_estimators': 67, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 14 with value: 0.824846400787152.

🏃 View run 16 at: http://127.0.0.1:5000/#/experiments/1/runs/51f1693a8f824c5e92455710d838b49a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:42,147] Trial 17 finished with value: 0.8235153205756914 and parameters: {'n_estimators': 90, 'max_depth': 17, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 14 with value: 0.824846400787152.

🏃 View run 17 at: http://127.0.0.1:5000/#/experiments/1/runs/71af48b0d1414df09fe32e13dc7f960c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:42,854] Trial 18 finished with value: 0.8255546863202033 and parameters: {'n_estimators': 115, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 18 with value: 0.8255546863202033.

🏃 View run 18 at: http://127.0.0.1:5000/#/experiments/1/runs/c3dae9a6047944dbb2e2c263d0b90c51
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:43,542] Trial 19 finished with value: 0.823293445222047 and parameters: {'n_estimators': 147, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 18 with value: 0.8255546863202033.

🏃 View run 19 at: http://127.0.0.1:5000/#/experiments/1/runs/0600429d8688428992543e6de2e32a05
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:44,128] Trial 20 finished with value: 0.817217490022609 and parameters: {'n_estimators': 112, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 18 with value: 0.8255546863202033.

🏃 View run 20 at: http://127.0.0.1:5000/#/experiments/1/runs/de70201f2c1a4e7fac139e607c21b6c4
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:44,795] Trial 21 finished with value: 0.8249382756594028 and parameters: {'n_estimators': 89, 'max_depth': 19, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 18 with value: 0.8255546863202033.

🏃 View run 21 at: http://127.0.0.1:5000/#/experiments/1/runs/59d1c9166c544cbcb9cef6e9ff8cec42
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:45,382] Trial 22 finished with value: 0.8240691253483675 and parameters: {'n_estimators': 91, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 18 with value: 0.8255546863202033.

🏃 View run 22 at: http://127.0.0.1:5000/#/experiments/1/runs/deb8a5c1097c4917b3d754039fba1675
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:46,180] Trial 23 finished with value: 0.8237926788760896 and parameters: {'n_estimators': 118, 'max_depth': 19, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 18 with value: 0.8255546863202033.

🏃 View run 23 at: http://127.0.0.1:5000/#/experiments/1/runs/4b73bb27cd8d4feaa28e1bf2815380a1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:46,777] Trial 24 finished with value: 0.8245038195375536 and parameters: {'n_estimators': 90, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 18 with value: 0.8255546863202033.

🏃 View run 24 at: http://127.0.0.1:5000/#/experiments/1/runs/ab348f4ff38a44e489cbd7b993b64553
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:47,538] Trial 25 finished with value: 0.8184030699104001 and parameters: {'n_estimators': 143, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 18 with value: 0.8255546863202033.

🏃 View run 25 at: http://127.0.0.1:5000/#/experiments/1/runs/10e3f3dcd10a40248dcacb652d44b037
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:48,276] Trial 26 finished with value: 0.8255546863202033 and parameters: {'n_estimators': 115, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 18 with value: 0.8255546863202033.

🏃 View run 26 at: http://127.0.0.1:5000/#/experiments/1/runs/749867a44ec44f06bd82ba7ef57ce9b3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:49,069] Trial 27 finished with value: 0.8236384449305116 and parameters: {'n_estimators': 117, 'max_depth': 19, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 18 with value: 0.8255546863202033.

🏃 View run 27 at: http://127.0.0.1:5000/#/experiments/1/runs/ffb2601c748d477e99e2cdfb5975374b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:50,235] Trial 28 finished with value: 0.8232630274118194 and parameters: {'n_estimators': 191, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 18 with value: 0.8255546863202033.

🏃 View run 28 at: http://127.0.0.1:5000/#/experiments/1/runs/6446088cb5dd43f3a14cde1784250d5e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:51,145] Trial 29 finished with value: 0.8227537560676907 and parameters: {'n_estimators': 136, 'max_depth': 21, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 18 with value: 0.8255546863202033.

🏃 View run 29 at: http://127.0.0.1:5000/#/experiments/1/runs/c1941d8b347d4211a2ced6b23a955d65
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:51,964] Trial 30 finished with value: 0.8236589149170115 and parameters: {'n_estimators': 120, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 18 with value: 0.8255546863202033.

🏃 View run 30 at: http://127.0.0.1:5000/#/experiments/1/runs/4938b198d08e423685e4bbc77dfee137
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:52,539] Trial 31 finished with value: 0.8255582823979553 and parameters: {'n_estimators': 91, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 31 with value: 0.8255582823979553.

🏃 View run 31 at: http://127.0.0.1:5000/#/experiments/1/runs/6f99511962c948468c37061e3302f428
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:53,214] Trial 32 finished with value: 0.8220859617125831 and parameters: {'n_estimators': 105, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 31 with value: 0.8255582823979553.

🏃 View run 32 at: http://127.0.0.1:5000/#/experiments/1/runs/8f8d870eb0234f6db24cbbf82add1aaf
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:53,740] Trial 33 finished with value: 0.8189949693779881 and parameters: {'n_estimators': 91, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 31 with value: 0.8255582823979553.

🏃 View run 33 at: http://127.0.0.1:5000/#/experiments/1/runs/7592f4611e2144c782220f0267ffea03
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:54,459] Trial 34 finished with value: 0.8237926788760896 and parameters: {'n_estimators': 109, 'max_depth': 17, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 31 with value: 0.8255582823979553.

🏃 View run 34 at: http://127.0.0.1:5000/#/experiments/1/runs/ee64796dfe674c8e935d27cbe3100304
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:55,111] Trial 35 finished with value: 0.8045227492797747 and parameters: {'n_estimators': 159, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 31 with value: 0.8255582823979553.
/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:55,286] Trial 36 finished with value: 0.7644287688004019 and parameters: {'n_estimators': 96, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 31 with value: 0.8255582823979553.

🏃 View run 35 at: http://127.0.0.1:5000/#/experiments/1/runs/ef76da83694f49c0868de153f6604eb7
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run 36 at: http://127.0.0.1:5000/#/experiments/1/runs/d1aedc3c65f74189a5a117d563c67fa7
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:55,962] Trial 37 finished with value: 0.8249067958417154 and parameters: {'n_estimators': 112, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 31 with value: 0.8255582823979553.

🏃 View run 37 at: http://127.0.0.1:5000/#/experiments/1/runs/a8b3fcffb9264573bbf15d17d4f0f71a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:56,186] Trial 38 finished with value: 0.7451784194441866 and parameters: {'n_estimators': 128, 'max_depth': 16, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 31 with value: 0.8255582823979553.

🏃 View run 38 at: http://127.0.0.1:5000/#/experiments/1/runs/bbda836087954056a63ceeb16ea0f94d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:56,883] Trial 39 finished with value: 0.8255895151785009 and parameters: {'n_estimators': 99, 'max_depth': 18, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 39 with value: 0.8255895151785009.

🏃 View run 39 at: http://127.0.0.1:5000/#/experiments/1/runs/b30a86a0aa4f4e97bb6bc96eb9ca2851
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:57,440] Trial 40 finished with value: 0.8188471540200317 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 39 with value: 0.8255895151785009.

🏃 View run 40 at: http://127.0.0.1:5000/#/experiments/1/runs/df576cf35993437d97527275f1cb59d3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:58,045] Trial 41 finished with value: 0.8250009576495108 and parameters: {'n_estimators': 84, 'max_depth': 18, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 39 with value: 0.8255895151785009.

🏃 View run 41 at: http://127.0.0.1:5000/#/experiments/1/runs/b66dac7718ec495a842a5e6a50e9c1d3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:58,625] Trial 42 finished with value: 0.8249085087314884 and parameters: {'n_estimators': 83, 'max_depth': 17, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 39 with value: 0.8255895151785009.

🏃 View run 42 at: http://127.0.0.1:5000/#/experiments/1/runs/97294660b9f6456e820373c10d99687a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:59,091] Trial 43 finished with value: 0.8259298974644069 and parameters: {'n_estimators': 62, 'max_depth': 16, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 43 with value: 0.8259298974644069.
/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:59,228] Trial 44 finished with value: 0.7680755161621404 and parameters: {'n_estimators': 55, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 43 with value: 0.8259298974644069.

🏃 View run 43 at: http://127.0.0.1:5000/#/experiments/1/runs/0e1c9fd3a071492d85753812a80afd2e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run 44 at: http://127.0.0.1:5000/#/experiments/1/runs/8d27c206b95b43ba98be205db05841f7
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:59,673] Trial 45 finished with value: 0.8218362618309552 and parameters: {'n_estimators': 68, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 43 with value: 0.8259298974644069.
/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:20:59,829] Trial 46 finished with value: 0.8142542947723078 and parameters: {'n_estimators': 60, 'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 43 with value: 0.8259298974644069.

🏃 View run 45 at: http://127.0.0.1:5000/#/experiments/1/runs/dc8fc70ed122490d9558c2991a51d992
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run 46 at: http://127.0.0.1:5000/#/experiments/1/runs/9a8e011b536747adac15a32c158093ee
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:21:00,441] Trial 47 finished with value: 0.8227208638340103 and parameters: {'n_estimators': 101, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 43 with value: 0.8259298974644069.

🏃 View run 47 at: http://127.0.0.1:5000/#/experiments/1/runs/9e6b18c8ea544394924f74abb4e1943d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:21:01,415] Trial 48 finished with value: 0.823010429834958 and parameters: {'n_estimators': 137, 'max_depth': 22, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 43 with value: 0.8259298974644069.

🏃 View run 48 at: http://127.0.0.1:5000/#/experiments/1/runs/ff9281c6246440ad862fd79810ad9aa5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:21:01,639] Trial 49 finished with value: 0.8070743070194649 and parameters: {'n_estimators': 125, 'max_depth': 26, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 43 with value: 0.8259298974644069.
INFO:app.train.train:Optimization complete!
INFO:app.train.train:Best f1: 0.8259
INFO:app.train.train:Best parameters: {'n_estimators': 62, 'max_depth': 16, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': None}

🏃 View run 49 at: http://127.0.0.1:5000/#/experiments/1/runs/61b100b086f847feba3f088a507fdac1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/mlflow/types/utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
2025/10/18 17:21:02 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/10/18 17:21:04 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
INFO:app.train.train:Best Model MLflow Run ID: e46bcbb331344e1483d3c416f09d54d1
INFO:app.train.train:Tracking URI: http://127.0.0.1:5000
INFO:app.train.train:Train Accuracy: 0.8561
INFO:app.train.train:Test Accuracy: 0.8244

🏃 View run best_model_RandomForestClassifier at: http://127.0.0.1:5000/#/experiments/1/runs/e46bcbb331344e1483d3c416f09d54d1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

In [10]:
print(f"Best MLflow run ID: {run_id}")  
print(f"Best hyperparameters: {study.best_params}")

Best MLflow run ID: e46bcbb331344e1483d3c416f09d54d1
Best hyperparameters: {'n_estimators': 62, 'max_depth': 16, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': None}