In [1]:
from app.data.etl import GetData
from app.data.feature_engineering import FeatureEngineering

In [2]:
get_data = GetData(file_path='app/data/raw_data/BD_ordenes.xlsx')
df = get_data.read_data()

In [3]:
df.head()

,respuesta,consumo_criticado,servicio,categoria,nivel_tension,estrato,localidad,funcion_analisis,calificacion,obs_lectura,periodicidad
0,1,0.0,701-ENERGÍA MDO REGULADO,3-INDUSTRIAL,220.0,NaN,5088-BELLO,CALCCOPR - Calcular Consumo Penalizado de Ener...,5035-BAJO ENERGIA (<-50%),30-VARIACION NIVEL DE UTILIZACIÓN,1
1,1,420.0,701-ENERGÍA MDO REGULADO,3-INDUSTRIAL,220.0,NaN,5088-BELLO,CALCCOPR - Calcular Consumo Penalizado de Ener...,5080-MUY ALTO (>500%),30-VARIACION NIVEL DE UTILIZACIÓN,1
2,1,99999.0,101-AGUA POTABLE,1-RESIDENCIAL,NaN,1.0,5088-BELLO,CALCCOLE - Calcular Consumo por Lecturas,5080-MUY ALTO (>500%),34-LECTURA MENOR,1
3,1,881.0,701-ENERGÍA MDO REGULADO,3-INDUSTRIAL,220.0,NaN,5088-BELLO,CALCCOLE - Calcular Consumo por Lecturas,5080-MUY ALTO (>500%),35-NO HAY JUSTIFICACION,1
4,1,99999.0,701-ENERGÍA MDO REGULADO,1-RESIDENCIAL,220.0,4.0,5001-MEDELLÍN,CALCCOLE - Calcular Consumo por Lecturas,5080-MUY ALTO (>500%),34-LECTURA MENOR,1

# Feature Engineering

In [4]:
feature_engineering = FeatureEngineering(df)
df_fe, target_variable, numeric_features, categorical_features = feature_engineering.prepare_features_only_energy()

In [5]:
print("Numeric features:", numeric_features)
print("Categorical features:", categorical_features)
print("Target variable:", target_variable)

Numeric features: ['consumo_criticado', 'nivel_tension', 'estrato', 'periodicidad']
Categorical features: ['categoria', 'localidad', 'funcion_analisis', 'calificacion', 'obs_lectura', 'tipo_servicio']
Target variable: respuesta

In [6]:
df_fe.head()

,respuesta,consumo_criticado,categoria,nivel_tension,estrato,localidad,funcion_analisis,calificacion,obs_lectura,periodicidad,tipo_servicio
0,0,0.0,3-INDUSTRIAL,220.0,NaN,5088-BELLO,CALCCOPR - Calcular Consumo Penalizado de Ener...,5035-BAJO ENERGIA (<-50%),30-VARIACION NIVEL DE UTILIZACIÓN,1,Energia
1,0,420.0,3-INDUSTRIAL,220.0,NaN,5088-BELLO,CALCCOPR - Calcular Consumo Penalizado de Ener...,5080-MUY ALTO (>500%),30-VARIACION NIVEL DE UTILIZACIÓN,1,Energia
3,0,881.0,3-INDUSTRIAL,220.0,NaN,5088-BELLO,CALCCOLE - Calcular Consumo por Lecturas,5080-MUY ALTO (>500%),35-NO HAY JUSTIFICACION,1,Energia
4,0,99999.0,1-RESIDENCIAL,220.0,4.0,5001-MEDELLÍN,CALCCOLE - Calcular Consumo por Lecturas,5080-MUY ALTO (>500%),34-LECTURA MENOR,1,Energia
7,0,260.0,3-INDUSTRIAL,220.0,NaN,5088-BELLO,CALCCOLE - Calcular Consumo por Lecturas,5035-BAJO ENERGIA (<-50%),30-VARIACION NIVEL DE UTILIZACIÓN,1,Energia

In [7]:
test_size = 0.2

# Modelo con MLFlow + Optuna

Antes de ejecutar, subir cliente de MLFlow con el comando.

* mlflow server --backend-store-uri sqlite:///consumos.db

In [8]:
from sklearn.ensemble import RandomForestClassifier
from app.train.train import TrainModel
import mlflow

mlflow.set_tracking_uri("http://127.0.0.1:5000")

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [9]:
# Define RandomForest parameter distributions
param_distributions = {
    'n_estimators': ('int', 50, 200),
    'max_depth': ('int', 5, 30),
    'min_samples_split': ('int', 2, 10),
    'min_samples_leaf': ('int', 1, 5),
    'max_features': ('categorical', ['sqrt', 'log2', None])
}

trainer = TrainModel(
    df_fe,
    numeric_features = numeric_features,
    categorical_features = categorical_features,
    target_column = target_variable,
    model_class = RandomForestClassifier,
    test_size = test_size,
    model_params = {'random_state': 42, 'n_jobs': -1},
    param_distributions = param_distributions,
    n_trials = 20,
    optimization_metric = 'f1',
    mlflow_setup = mlflow,
    mlflow_registered_model_name = "RF_Desviacion_Consumos"
)

best_pipeline, run_id, study = trainer.train()

[I 2025-10-18 17:45:18,757] A new study created in memory with name: optuna_RandomForestClassifier
/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/src/app/train/train.py:186: ExperimentalWarning: MLflowCallback is experimental (supported from v1.4.0). The interface can change in the future.
  mlflow_callback = MLflowCallback(
INFO:app.train.train:Starting Optuna optimization with 20 trials...
INFO:app.train.train:Optimizing for: f1
INFO:app.train.train:Model type: RandomForestClassifier
/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:18,969] Trial 0 finished with value: 0.8015627747900393 and parameters: {'n_estimators': 108, 'max_depth': 30, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 0 with value: 0.8015627747900393.
2025/10/18 17:45:19 INFO mlflow.tracking.fluent: Experiment with name 'optuna_RandomForestClassifier' does not exist. Creating a new experiment.
/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:19,390] Trial 1 finished with value: 0.759483196146882 and parameters: {'n_estimators': 57, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 0 with value: 0.8015627747900393.

🏃 View run 0 at: http://127.0.0.1:5000/#/experiments/1/runs/ebf7d8ebe4e745efb2b831b41fff4e67
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run 1 at: http://127.0.0.1:5000/#/experiments/1/runs/7aafd43733a24fd598add8995c7548a6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:20,737] Trial 2 finished with value: 0.822801590286785 and parameters: {'n_estimators': 194, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 2 with value: 0.822801590286785.

🏃 View run 2 at: http://127.0.0.1:5000/#/experiments/1/runs/80b365d36e034f79a7ccfb35f8ed6c6a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:21,723] Trial 3 finished with value: 0.8257440833663792 and parameters: {'n_estimators': 166, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 3 with value: 0.8257440833663792.
/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:21,929] Trial 4 finished with value: 0.6864372700808955 and parameters: {'n_estimators': 134, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 3 with value: 0.8257440833663792.

🏃 View run 3 at: http://127.0.0.1:5000/#/experiments/1/runs/656d3e61d265440cb98ab0f3082528b6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run 4 at: http://127.0.0.1:5000/#/experiments/1/runs/9558faa1dd9a49f5b00d7797badcd84c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:22,255] Trial 5 finished with value: 0.8160879568971783 and parameters: {'n_estimators': 186, 'max_depth': 24, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 3 with value: 0.8257440833663792.

🏃 View run 5 at: http://127.0.0.1:5000/#/experiments/1/runs/e1b849a69f874c4a8b59b31cd09e31e8
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:22,496] Trial 6 finished with value: 0.8253545620533529 and parameters: {'n_estimators': 109, 'max_depth': 25, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 3 with value: 0.8257440833663792.

🏃 View run 6 at: http://127.0.0.1:5000/#/experiments/1/runs/d8b5b509f47747599cdc411716990f78
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:23,171] Trial 7 finished with value: 0.8244124849205415 and parameters: {'n_estimators': 87, 'max_depth': 17, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 3 with value: 0.8257440833663792.

🏃 View run 7 at: http://127.0.0.1:5000/#/experiments/1/runs/ac1fb6d4c3154feda806d14ec3c2f9bf
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:23,431] Trial 8 finished with value: 0.8136195948625768 and parameters: {'n_estimators': 109, 'max_depth': 18, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 3 with value: 0.8257440833663792.

🏃 View run 8 at: http://127.0.0.1:5000/#/experiments/1/runs/611ceae2f1a841ffbae25f1837c40019
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:23,717] Trial 9 finished with value: 0.8060587512381339 and parameters: {'n_estimators': 60, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 3 with value: 0.8257440833663792.

🏃 View run 9 at: http://127.0.0.1:5000/#/experiments/1/runs/a4fb001dd7a14950a711329562cbc1cc
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:24,287] Trial 10 finished with value: 0.797889448301958 and parameters: {'n_estimators': 158, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 3 with value: 0.8257440833663792.

🏃 View run 10 at: http://127.0.0.1:5000/#/experiments/1/runs/f22816bfca21498282342427e359ca28
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:24,611] Trial 11 finished with value: 0.8272236262465439 and parameters: {'n_estimators': 146, 'max_depth': 27, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8272236262465439.

🏃 View run 11 at: http://127.0.0.1:5000/#/experiments/1/runs/c1a8dde2f3904d5cbbac9dc35365a700
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:24,875] Trial 12 finished with value: 0.7511702583155435 and parameters: {'n_estimators': 161, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8272236262465439.

🏃 View run 12 at: http://127.0.0.1:5000/#/experiments/1/runs/0a39993ec13c4da4b87e7d3ffdb28d17
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:26,012] Trial 13 finished with value: 0.8196604103431742 and parameters: {'n_estimators': 153, 'max_depth': 30, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 11 with value: 0.8272236262465439.

🏃 View run 13 at: http://127.0.0.1:5000/#/experiments/1/runs/9a57a45123c04aceb7128b5f6011f09a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:26,341] Trial 14 finished with value: 0.8178494648890672 and parameters: {'n_estimators': 173, 'max_depth': 23, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8272236262465439.

🏃 View run 14 at: http://127.0.0.1:5000/#/experiments/1/runs/e50d4162787f419db02b4d55ef702d91
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:27,066] Trial 15 finished with value: 0.8192902822986604 and parameters: {'n_estimators': 134, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 11 with value: 0.8272236262465439.

🏃 View run 15 at: http://127.0.0.1:5000/#/experiments/1/runs/b990dc1f0713478296a40dd490e7b08c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:27,321] Trial 16 finished with value: 0.8151596597716968 and parameters: {'n_estimators': 145, 'max_depth': 27, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8272236262465439.

🏃 View run 16 at: http://127.0.0.1:5000/#/experiments/1/runs/563d4f2ddb794e29927cd29947423f3b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:28,425] Trial 17 finished with value: 0.8236978669292302 and parameters: {'n_estimators': 177, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 11 with value: 0.8272236262465439.

🏃 View run 17 at: http://127.0.0.1:5000/#/experiments/1/runs/e8e4b0c1b4a24d159839d76392f170ea
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:28,649] Trial 18 finished with value: 0.8061424545617839 and parameters: {'n_estimators': 124, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8272236262465439.
/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:28,826] Trial 19 finished with value: 0.753520778667868 and parameters: {'n_estimators': 85, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 11 with value: 0.8272236262465439.
INFO:app.train.train:Optimization complete!
INFO:app.train.train:Best f1: 0.8272
INFO:app.train.train:Best parameters: {'n_estimators': 146, 'max_depth': 27, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'sqrt'}

🏃 View run 18 at: http://127.0.0.1:5000/#/experiments/1/runs/8d107ae1713a4ebcb0f9d7c626559c28
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run 19 at: http://127.0.0.1:5000/#/experiments/1/runs/56b441187c6c4026acb7d8fcaf028c25
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/mlflow/types/utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
2025/10/18 17:45:29 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/10/18 17:45:31 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'RF_Desviacion_Consumos'.
2025/10/18 17:45:31 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: RF_Desviacion_Consumos, version 1
Created version '1' of model 'RF_Desviacion_Consumos'.
INFO:app.train.train:Model successfully registered in Model Registry as: 'RF_Desviacion_Consumos'
INFO:app.train.train:Best Model MLflow Run ID: d669e1d726a24d538bdede523c8c0096
INFO:app.train.train:Tracking URI: http://127.0.0.1:5000
INFO:app.train.train:Train Accuracy: 0.8956
INFO:app.train.train:Test Accuracy: 0.8290

🏃 View run best_model_RandomForestClassifier at: http://127.0.0.1:5000/#/experiments/1/runs/d669e1d726a24d538bdede523c8c0096
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

In [10]:
print(f"Best MLflow run ID: {run_id}")  
print(f"Best hyperparameters: {study.best_params}")

Best MLflow run ID: d669e1d726a24d538bdede523c8c0096
Best hyperparameters: {'n_estimators': 146, 'max_depth': 27, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'sqrt'}

In [11]:
from xgboost import XGBClassifier

In [12]:
# Define XGBoost parameter distributions
param_distributions_xgb = {
    'n_estimators': ('int', 100, 1000),
    'max_depth': ('int', 3, 10),
    'learning_rate': ('float', 0.01, 0.3, True), # Log scale es bueno para learning rate
    'subsample': ('float', 0.5, 1.0),
    'colsample_bytree': ('float', 0.5, 1.0),
    'gamma': ('float', 0, 0.5),
    'reg_alpha': ('float', 1e-5, 1.0, True), # L1 regularization
    'reg_lambda': ('float', 1e-5, 1.0, True)  # L2 regularization
}

fixed_model_params_xgb = {
    'random_state': 42, 
    'n_jobs': -1,
    'objective': 'binary:logistic', # clasificación binaria
    'eval_metric': 'logloss' 
}

trainer_xgb = TrainModel(
    df_fe,
    numeric_features = numeric_features,
    categorical_features = categorical_features,
    target_column = target_variable,
    model_class = XGBClassifier,  # <-- Cambio clave
    test_size = test_size,
    model_params = fixed_model_params_xgb, # <-- Cambio clave
    param_distributions = param_distributions_xgb, # <-- Cambio clave
    n_trials = 20, # Puedes ajustar esto
    optimization_metric = 'roc_auc', # 'roc_auc' es excelente para XGBoost
    mlflow_setup = mlflow,
    mlflow_registered_model_name = "XGB_Desviacion_Consumos"  # Nombre para el registro del modelo
)

best_pipeline_xgb, run_id_xgb, study_xgb = trainer_xgb.train()

print("\n--- Entrenamiento de XGBoost completado ---")
print(f"Mejor Pipeline (XGB): {best_pipeline_xgb}")
print(f"MLflow Run ID (XGB): {run_id_xgb}")

[I 2025-10-18 17:45:45,022] A new study created in memory with name: optuna_XGBClassifier
/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/src/app/train/train.py:186: ExperimentalWarning: MLflowCallback is experimental (supported from v1.4.0). The interface can change in the future.
  mlflow_callback = MLflowCallback(
INFO:app.train.train:Starting Optuna optimization with 20 trials...
INFO:app.train.train:Optimizing for: roc_auc
INFO:app.train.train:Model type: XGBClassifier
/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:45,859] Trial 0 finished with value: 0.9002075794972563 and parameters: {'n_estimators': 602, 'max_depth': 5, 'learning_rate': 0.2087938899780242, 'subsample': 0.8413411566717752, 'colsample_bytree': 0.9468754767021998, 'gamma': 0.4086668982590917, 'reg_alpha': 2.6947305038517555e-05, 'reg_lambda': 1.7660451543638638e-05}. Best is trial 0 with value: 0.9002075794972563.
2025/10/18 17:45:45 INFO mlflow.tracking.fluent: Experiment with name 'optuna_XGBClassifier' does not exist. Creating a new experiment.

🏃 View run 0 at: http://127.0.0.1:5000/#/experiments/2/runs/fc516f5862694d8a96ceb7d4e2602901
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:46,238] Trial 1 finished with value: 0.8961358662225524 and parameters: {'n_estimators': 301, 'max_depth': 4, 'learning_rate': 0.12800419530381202, 'subsample': 0.9976741503607557, 'colsample_bytree': 0.9330804780992166, 'gamma': 0.4587475359910426, 'reg_alpha': 1.620311061469145e-05, 'reg_lambda': 0.0007631871901243023}. Best is trial 0 with value: 0.9002075794972563.

🏃 View run 1 at: http://127.0.0.1:5000/#/experiments/2/runs/ddd7f574b693479a96873edd0aa1187d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:46,710] Trial 2 finished with value: 0.9001969958384255 and parameters: {'n_estimators': 312, 'max_depth': 5, 'learning_rate': 0.17913906943342622, 'subsample': 0.744548322549925, 'colsample_bytree': 0.9203994835965976, 'gamma': 0.24705913644492555, 'reg_alpha': 4.1357917047279264e-05, 'reg_lambda': 1.0666834700708342e-05}. Best is trial 0 with value: 0.9002075794972563.

🏃 View run 2 at: http://127.0.0.1:5000/#/experiments/2/runs/11ac3c63d4bb4d72ba6b6e3b99d1833f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:47,223] Trial 3 finished with value: 0.8964296126780251 and parameters: {'n_estimators': 470, 'max_depth': 3, 'learning_rate': 0.19649066275553975, 'subsample': 0.6786393380059658, 'colsample_bytree': 0.7855282236853112, 'gamma': 0.04752787254321289, 'reg_alpha': 0.0004060889594118891, 'reg_lambda': 0.034288129628372285}. Best is trial 0 with value: 0.9002075794972563.

🏃 View run 3 at: http://127.0.0.1:5000/#/experiments/2/runs/9d96474257c343d388490cc54f22b4d8
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:47,673] Trial 4 finished with value: 0.8944285023923063 and parameters: {'n_estimators': 293, 'max_depth': 5, 'learning_rate': 0.05474476418048235, 'subsample': 0.9618878828557906, 'colsample_bytree': 0.599761156668056, 'gamma': 0.3391415595642504, 'reg_alpha': 0.012497081380746632, 'reg_lambda': 0.015203214616153364}. Best is trial 0 with value: 0.9002075794972563.

🏃 View run 4 at: http://127.0.0.1:5000/#/experiments/2/runs/e5ea77146b684d489fcd8409490a2772
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:48,883] Trial 5 finished with value: 0.8964084453603636 and parameters: {'n_estimators': 664, 'max_depth': 8, 'learning_rate': 0.18422352510594725, 'subsample': 0.9476249540857844, 'colsample_bytree': 0.75852335817765, 'gamma': 0.17717844879147732, 'reg_alpha': 0.005447441521607428, 'reg_lambda': 0.00838960328799156}. Best is trial 0 with value: 0.9002075794972563.

🏃 View run 5 at: http://127.0.0.1:5000/#/experiments/2/runs/817202d1abc6406fb7e1dfc2f464d160
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:49,318] Trial 6 finished with value: 0.8943677961227865 and parameters: {'n_estimators': 178, 'max_depth': 9, 'learning_rate': 0.2150443985724072, 'subsample': 0.5872238059404951, 'colsample_bytree': 0.7797073047676308, 'gamma': 0.3178593344771738, 'reg_alpha': 0.00043288969957814394, 'reg_lambda': 4.0014101760178477e-05}. Best is trial 0 with value: 0.9002075794972563.

🏃 View run 6 at: http://127.0.0.1:5000/#/experiments/2/runs/93d29ef72c604c4ab1b1e216f6c7f533
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:50,346] Trial 7 finished with value: 0.9004743675764622 and parameters: {'n_estimators': 805, 'max_depth': 8, 'learning_rate': 0.1538145954371228, 'subsample': 0.9367187474699763, 'colsample_bytree': 0.5050443199912467, 'gamma': 0.2785587362048139, 'reg_alpha': 0.24550136063523004, 'reg_lambda': 0.3818792215132883}. Best is trial 7 with value: 0.9004743675764622.

🏃 View run 7 at: http://127.0.0.1:5000/#/experiments/2/runs/2a31b205d755400c9da7d8e369a90f40
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:50,650] Trial 8 finished with value: 0.8968523599562275 and parameters: {'n_estimators': 138, 'max_depth': 7, 'learning_rate': 0.06560933314595577, 'subsample': 0.6068283105131986, 'colsample_bytree': 0.8917713511846332, 'gamma': 0.26356582262169287, 'reg_alpha': 1.0809450134574867e-05, 'reg_lambda': 0.05247486984671563}. Best is trial 7 with value: 0.9004743675764622.

🏃 View run 8 at: http://127.0.0.1:5000/#/experiments/2/runs/8dc856ae5c924093a956f31b9a925ac5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:51,556] Trial 9 finished with value: 0.8973051608316759 and parameters: {'n_estimators': 909, 'max_depth': 3, 'learning_rate': 0.16405646216143227, 'subsample': 0.6196891704386736, 'colsample_bytree': 0.9346340328901901, 'gamma': 0.49243261235802416, 'reg_alpha': 4.86257262053379e-05, 'reg_lambda': 0.00023064024032485445}. Best is trial 7 with value: 0.9004743675764622.

🏃 View run 9 at: http://127.0.0.1:5000/#/experiments/2/runs/f3292009a6c248be8e156cd6c4e88dcf
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:53,838] Trial 10 finished with value: 0.9010500786785204 and parameters: {'n_estimators': 970, 'max_depth': 10, 'learning_rate': 0.012895909051606818, 'subsample': 0.8590682125491691, 'colsample_bytree': 0.5332554344977538, 'gamma': 0.12078039058833145, 'reg_alpha': 0.8068158855215044, 'reg_lambda': 0.6707301338045326}. Best is trial 10 with value: 0.9010500786785204.

🏃 View run 10 at: http://127.0.0.1:5000/#/experiments/2/runs/ce9c4dd8b2b443d987b4c2e2f2de8f7f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:56,090] Trial 11 finished with value: 0.8994816004089685 and parameters: {'n_estimators': 975, 'max_depth': 10, 'learning_rate': 0.010090964473008456, 'subsample': 0.8382948143971858, 'colsample_bytree': 0.5006762638322002, 'gamma': 0.09603197523453683, 'reg_alpha': 0.6723711688232845, 'reg_lambda': 0.6812396800738669}. Best is trial 10 with value: 0.9010500786785204.

🏃 View run 11 at: http://127.0.0.1:5000/#/experiments/2/runs/763d98aeda2f4fd9b75368c644d60515
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:58,055] Trial 12 finished with value: 0.8990422787216539 and parameters: {'n_estimators': 836, 'max_depth': 10, 'learning_rate': 0.01156935343491924, 'subsample': 0.8546228342056238, 'colsample_bytree': 0.504704688910959, 'gamma': 0.15185940491927313, 'reg_alpha': 0.8739942400861156, 'reg_lambda': 0.9762359706374066}. Best is trial 10 with value: 0.9010500786785204.

🏃 View run 12 at: http://127.0.0.1:5000/#/experiments/2/runs/9d3218d7a9f342eeac49399fcf620523
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:45:59,560] Trial 13 finished with value: 0.90198992755186 and parameters: {'n_estimators': 765, 'max_depth': 8, 'learning_rate': 0.02351162314510717, 'subsample': 0.9036155978309903, 'colsample_bytree': 0.6222350655158838, 'gamma': 0.1836048670475094, 'reg_alpha': 0.07707851391149405, 'reg_lambda': 0.16290418795931078}. Best is trial 13 with value: 0.90198992755186.

🏃 View run 13 at: http://127.0.0.1:5000/#/experiments/2/runs/669a512c993e479ea6116b4c6a3f9bd3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:46:01,155] Trial 14 finished with value: 0.9019307189699104 and parameters: {'n_estimators': 744, 'max_depth': 9, 'learning_rate': 0.019993775757353827, 'subsample': 0.7587351166408988, 'colsample_bytree': 0.6328592332264947, 'gamma': 0.02023266543405572, 'reg_alpha': 0.07029857055360755, 'reg_lambda': 0.13526876679107247}. Best is trial 13 with value: 0.90198992755186.

🏃 View run 14 at: http://127.0.0.1:5000/#/experiments/2/runs/8d474b8df3514c57a6baa746e7d2f54d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:46:02,426] Trial 15 finished with value: 0.9005160032909189 and parameters: {'n_estimators': 718, 'max_depth': 7, 'learning_rate': 0.021593214060931582, 'subsample': 0.7568968230189765, 'colsample_bytree': 0.6382515062575401, 'gamma': 0.0538207297810441, 'reg_alpha': 0.07322187899737856, 'reg_lambda': 0.11713757780664932}. Best is trial 13 with value: 0.90198992755186.

🏃 View run 15 at: http://127.0.0.1:5000/#/experiments/2/runs/175fb11a07d64383a8ce39d76a880641
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:46:03,461] Trial 16 finished with value: 0.9010917143929773 and parameters: {'n_estimators': 507, 'max_depth': 8, 'learning_rate': 0.027083516925128392, 'subsample': 0.5113304711619553, 'colsample_bytree': 0.6783916136697017, 'gamma': 0.006602876178798598, 'reg_alpha': 0.01922290636298372, 'reg_lambda': 0.0020165217169147514}. Best is trial 13 with value: 0.90198992755186.

🏃 View run 16 at: http://127.0.0.1:5000/#/experiments/2/runs/dc0673609e8948bc88342932a1f86f9c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:46:05,081] Trial 17 finished with value: 0.9024682889618427 and parameters: {'n_estimators': 756, 'max_depth': 9, 'learning_rate': 0.028212674990426, 'subsample': 0.7337306614305988, 'colsample_bytree': 0.6931404846836668, 'gamma': 0.19801849988793252, 'reg_alpha': 0.07494076811439954, 'reg_lambda': 0.13029323084017735}. Best is trial 17 with value: 0.9024682889618427.

🏃 View run 17 at: http://127.0.0.1:5000/#/experiments/2/runs/5b95da070cff4c32b5dc0af332b240ef
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:46:06,015] Trial 18 finished with value: 0.9018991676850943 and parameters: {'n_estimators': 591, 'max_depth': 6, 'learning_rate': 0.04579054331734224, 'subsample': 0.676141944768122, 'colsample_bytree': 0.7198206939711853, 'gamma': 0.21067452972183007, 'reg_alpha': 0.0012183026406189102, 'reg_lambda': 0.005095124927813774}. Best is trial 17 with value: 0.9024682889618427.

🏃 View run 18 at: http://127.0.0.1:5000/#/experiments/2/runs/b5d395a680424de3965ca2551f2d1cb7
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[I 2025-10-18 17:46:07,820] Trial 19 finished with value: 0.902169749906145 and parameters: {'n_estimators': 846, 'max_depth': 9, 'learning_rate': 0.03223246322412124, 'subsample': 0.7973421081007609, 'colsample_bytree': 0.5746172188074012, 'gamma': 0.1941063270159612, 'reg_alpha': 0.07321295967907232, 'reg_lambda': 0.16937355503849716}. Best is trial 17 with value: 0.9024682889618427.
INFO:app.train.train:Optimization complete!
INFO:app.train.train:Best roc_auc: 0.9025
INFO:app.train.train:Best parameters: {'n_estimators': 756, 'max_depth': 9, 'learning_rate': 0.028212674990426, 'subsample': 0.7337306614305988, 'colsample_bytree': 0.6931404846836668, 'gamma': 0.19801849988793252, 'reg_alpha': 0.07494076811439954, 'reg_lambda': 0.13029323084017735}

🏃 View run 19 at: http://127.0.0.1:5000/#/experiments/2/runs/51fc7be48322481b8c5e8a1c1678334b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Users/jonatanlondonotaborda/Documents/Repositorios/Proyecto1_UdeM/.venv/lib/python3.12/site-packages/mlflow/types/utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
2025/10/18 17:46:09 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/10/18 17:46:10 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Successfully registered model 'XGB_Desviacion_Consumos'.
2025/10/18 17:46:11 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: XGB_Desviacion_Consumos, version 1
Created version '1' of model 'XGB_Desviacion_Consumos'.
INFO:app.train.train:Model successfully registered in Model Registry as: 'XGB_Desviacion_Consumos'
INFO:app.train.train:Best Model MLflow Run ID: 09c9684c0e384d418e62bf214404b2d1
INFO:app.train.train:Tracking URI: http://127.0.0.1:5000
INFO:app.train.train:Train Accuracy: 0.8719
INFO:app.train.train:Test Accuracy: 0.8309

🏃 View run best_model_XGBClassifier at: http://127.0.0.1:5000/#/experiments/2/runs/09c9684c0e384d418e62bf214404b2d1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

--- Entrenamiento de XGBoost completado ---
Mejor Pipeline (XGB): Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['consumo_criticado',
                                                   'nivel_tension', 'estrato',
                                                   'periodicidad']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(fill_value='Unknown',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(drop='fir...
                               gamma=0.19801849988793252, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None,
                               learning_rate=0.028212674990426, max_bin=None,
                               max_cat_threshold=None, max_cat_to_onehot=None,
                               max_delta_step=None, max_depth=9,
                               max_leaves=None, min_child_weight=None,
                               missing=nan, monotone_constraints=None,
                               multi_strategy=None, n_estimators=756, n_jobs=-1,
                               num_parallel_tree=None, ...))])
MLflow Run ID (XGB): 09c9684c0e384d418e62bf214404b2d1